server {
    listen 80;
    server_name buku-tamu.example.go.id;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name buku-tamu.example.go.id;
    root /var/www/buku-tamu/public;
    index index.php;
    client_max_body_size 6M;

    ssl_certificate /etc/letsencrypt/live/buku-tamu.example.go.id/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/buku-tamu.example.go.id/privkey.pem;

    location / { try_files $uri $uri/ /index.php?$query_string; }
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.3-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
    }
    location ~ /\. { deny all; }
}
