<!DOCTYPE html><html lang="id"><head><meta charset="UTF-8"><title>Laporan Survei PTA Manado</title><style>
@page{margin:10mm 10mm 15mm}*{box-sizing:border-box}body{margin:0;color:#172033;font-family:"DejaVu Sans",sans-serif;font-size:7px}header{height:14mm;margin-bottom:6mm;border-bottom:2px solid #075985}.office{color:#075985;font-size:13px;font-weight:bold}.caption,.meta{color:#475569}footer{position:fixed;bottom:-10mm;left:0;right:0;color:#64748b}h1{margin:0;font-size:17px}.meta{margin:3px 0 8px}.filters{margin-bottom:8px;padding:6px;border:1px solid #cbd5e1;background:#f8fafc}.summary{width:100%;margin-bottom:8px;border-spacing:4px 0}.summary td{padding:6px;border:1px solid #bae6fd;background:#f0f9ff}.label{color:#475569;text-transform:uppercase}.value{font-size:13px;font-weight:bold;color:#0c4a6e}.distribution{margin-bottom:9px}.distribution span{display:inline-block;margin-right:8px;color:#92400e}table.detail{width:100%;border-collapse:collapse;table-layout:fixed}thead{display:table-header-group}tr{page-break-inside:avoid}th{padding:5px 3px;border:1px solid #0c4a6e;background:#075985;color:#fff;text-align:left}td{padding:4px 3px;border:1px solid #cbd5e1;vertical-align:top;line-height:1.3;overflow-wrap:break-word}.continuation{page-break-before:always}.center{text-align:center}.empty{padding:20px;text-align:center;color:#64748b}
</style></head><body>
<header><div class="office">PENGADILAN TINGGI AGAMA MANADO</div><div class="caption">Sistem Buku Tamu Digital - Evaluasi Kepuasan Pelayanan</div></header>
<footer>Dicetak {{ $generatedAt->translatedFormat('d F Y, H:i') }} WITA · Dokumen memuat data pribadi dan hanya untuk kepentingan dinas.</footer>
<main><h1>Laporan Hasil Survei Kepuasan</h1><div class="meta">Periode kunjungan {{ $filters->from->translatedFormat('d F Y') }} sampai {{ $filters->to->translatedFormat('d F Y') }}</div>
<div class="filters"><strong>Filter:</strong> Rating {{ $filters->rating ? $filters->rating.' bintang' : 'Semua' }}; Status {{ match($filters->responseStatus){'responded'=>'Sudah merespons','not_responded'=>'Belum merespons',default=>'Semua'} }}; Pegawai {{ $employee?->name ?? 'Semua' }}; Unit {{ $workUnit?->name ?? 'Semua' }}. Foto dan nomor WhatsApp tidak disertakan.</div>
<table class="summary"><tr><td><div class="label">Survei terkirim</div><div class="value">{{ $summary['sent'] }}</div></td><td><div class="label">Respons</div><div class="value">{{ $summary['responded'] }}</div></td><td><div class="label">Belum respons</div><div class="value">{{ $summary['not_responded'] }}</div></td><td><div class="label">Tingkat respons</div><div class="value">{{ number_format($summary['response_rate'],1) }}%</div></td><td><div class="label">Rata-rata</div><div class="value">{{ $summary['average_rating'] !== null ? number_format($summary['average_rating'],2) : '-' }}</div></td></tr></table>
<div class="distribution"><strong>Distribusi:</strong> @foreach($summary['distribution'] as $rating=>$count)<span>{{ $rating }} bintang: {{ $count }}</span>@endforeach</div>
@include('admin.reports.partials.survey-table',['items'=>$rows->take(4),'offset'=>0])
@foreach($rows->skip(4)->chunk(6) as $chunk)<div class="continuation">@include('admin.reports.partials.survey-table',['items'=>$chunk,'offset'=>4+($loop->index*6)])</div>@endforeach
</main></body></html>
