[program:buku-tamu-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/buku-tamu/artisan queue:work database --queue=notifications,default --sleep=1 --tries=3 --timeout=60 --max-time=3600
directory=/var/www/buku-tamu
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/buku-tamu/storage/logs/worker.log
stopwaitsecs=3600
